### ISSUE TITLE
`tput cols` always prints "80"

### ISSUE THREAD

**Issue by SirCmpwn** [sabotage-linux/netbsd-curses#26]

**Comment by SirCmpwn** [comment]
Using urxvt, also with TERM=xterm or with xterm proper.

**Comment by rofl0r** [comment]
thanks for the heads up. investigating.

**Comment by rofl0r** [comment]
i merged some changes, afaict this commit 541187d5b60e8747477088223acc960e69cebe71 should "fix" it.
i put "fix" into quotes, because according to roy smarples this is non-portable behaviour, according to POSIX it's required to return the initial cols value, and `stty size` should be used instead. he added it anyway though.

**Comment by SirCmpwn** [comment]
Thanks. I've been using `stty size` but figured I would mention the discrepancy with ncurses.

**Comment by rofl0r** [comment]
Thanks. I'm sure there's more than one script out there that relied on ncurses' behaviour, so it's good we've changed it.
