### ISSUE TITLE
Problems uninstalling

### ISSUE THREAD

**Issue by finnoleary** [sabotage-linux/netbsd-curses#31]
The makefile does not contain targets for uninstalling. This requires the user to figure out which files belong to netbsd-curses, and remove them manually.

**Comment by rofl0r** [comment]
this can be figured out quite easily:
`make DESTDIR=foo install` and you will have the entire tree in foo/.
then `find foo` and you have the list of files.
DESTDIR is also the mechanism packagers use to create their distros binary package.
if you build/install stuff from source, maybe you want to use that in combination with `stow` or something similar.
so since the install/uninstall is usually handled by 3rd party means (such as distro package manager, or stow), i don't really see a good reason to add an `uninstall` target, which can potentially harm the user's filesystem, if he makes an error or there's some bug. that's a can of worms i don't intend to open.
