### ISSUE TITLE
util-linux: more fails with tparm

### ISSUE THREAD

**Issue by firasuke** [sabotage-linux/netbsd-curses#58]
Hey there,

Thank you for your work on the project.

I came upon the following issue when building `util-linux`'s implementation of `more` using `netbsd-curses:
```c
text-utils/more.c: In function 'initterm':
text-utils/more.c:2052:39: error: too few arguments to function 'tparm'
 2052 |                         cursor_addr = tparm(cursor_addr, 0, 0);
      |                                       ^~~~~
In file included from text-utils/more.c:74:
cross/usr/include/term.h:1961:17: note: declared here
 1961 | char *          tparm(const char *, long, long, long, long, long,
      |                 ^~~~~
```

I was able to fix this issue by modifying `term.h` and changing tparm's definition to use varargs:
```c
...
char *		tparm(const char *, ...);
...
```

Is this intended? Also apparently `ncurses` provides two versions of `tparm` one with varargs? I also saw that `tiparm` exists and accepts varargs by default, should `more` be patched to use `tiparm` instead of `tparm`?

Thank in advance!

**Comment by rofl0r** [comment]
that's an issue that pop ups regularly. the curses specced tparm uses a fixed number of args, and the variadic version is a ncurses-ism. if a program wants to be portable, it needs to fill in the missing arguments with 0s, so that would be the right patch to submit to util-linux upstream.
you can look at KEEP/ne-curses.patch and KEEP/procps-ng-netbsd-curses.patch in sabotage repo for inspiration.

**Comment by firasuke** [comment]
Interesting, thanks for your input on this.

Feel free to close this issue if you want.
